kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: files-csi
    annotations:
        storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.nutanix.com
parameters:
    nfsServer: 10.45.20.190
    nfsPath: /csishare1
    storageType: NutanixFiles
reclaimPolicy: Delete
